name: PHP Composer

on:
  push:
    branches: [ "master", "feature/12-add-test-pipeline" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: Setup PHP without any shared extensions except mbstring
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer, phpunit

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: sudo composer install --prefer-dist

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: Setup PHP without any shared extensions except mbstring
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Run audit
        run: composer audit

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: Setup PHP without any shared extensions except mbstring
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer, phpunit

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: sudo composer install --prefer-dist

      - name: Run test suite
        run: ./vendor/bin/phpunit -c phpunit.xml.dist
